(function(g){var window=this;var tBa=function(a,b,c,d){c=(0,g.C)(c,d||a.A);b=g.LH(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},uBa=function(a){a.o||(a.o=new g.CE,g.M(a,a.o));
return a.o},j2=function(a){a.U("cardstatechange",a.be()&&a.se()?1:0)},yBa=function(a){var b=g.ii(a,"fontSize");
var c=(c=b.match(vBa))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.ie){if(String(c)in wBa)return g.Ai(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in xBa)return a=a.parentNode,c=g.ii(a,"fontSize"),g.Ai(a,b==c?"1em":b,"left","pixelLeft")}c=g.ne("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.ve(c);return b},k2=function(a,b){this.start=a<b?a:b;
this.end=a<b?b:a},zBa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Cl&&a.dataset){if(g.qc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Cd("pollChoiceIndex"))},n2=function(a){a=g.Ma(a);
delete l2[a];g.dc(l2)&&m2&&m2.stop()},BBa=function(){m2||(m2=new g.V(function(){ABa()},20));
var a=m2;a.isActive()||a.start()},ABa=function(){var a=(0,g.K)();
g.Pb(l2,function(b){CBa(b,a)});
g.dc(l2)||BBa()},DBa=function(a,b){g.Uf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},o2=function(a,b,c,d){g.cv.call(this);
if(!g.Ha(a)||!g.Ha(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.G=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.F=0;this.B=null},CBa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.B);a.B=b;EBa(a,a.progress);1==a.progress?(a.o=0,n2(a),a.Hd(),a.Dn()):a.sb()&&a.Kw()},EBa=function(a,b){g.Ja(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.G[c]-a.A[c])*b+a.A[c]},p2=function(a,b,c,d,e){o2.call(this,b,c,d,e);
this.element=a},q2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
p2.call(this,a,b,c,d,e)},FBa=function(a){return Math.pow(a,3)},GBa=function(a){return 3*a*a-2*a*a*a},r2=function(a,b){(0,g.E)(b,function(c){g.xI("visualElementShown",{csn:a,
ve:g.GI(c),eventType:4},g.CI,void 0,void 0)})},s2=function(a,b){(0,g.E)(b,function(c){g.xI("visualElementHidden",{csn:a,
ve:g.GI(c),eventType:8},g.CI,void 0,void 0)})},t2=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Jd=b.session_data||{};this.C=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.A={KM:a.impression,click:a.click,close:a.close,RV:a.teaser_impression,Ux:a.teaser_click};b=b.tracking_params||{};this.F=g.FI(b.card);this.H=g.FI(b.teaser);this.D=g.FI(b.icon)},u2=function(a,b){g.vg.call(this);
this.Gm=a;this.Hu=b;this[g.Zf]=!1},y2=function(a,b,c,d){u2.call(this,a,b);
a=this.Hu;b=this.sa();c?(b.setAttribute("stroke",c.o),b.setAttribute("stroke-opacity",1),c=c.ab(),g.x(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/HBa(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Hu;a=this.sa();if(d instanceof v2)a.setAttribute("fill",d.I),a.setAttribute("fill-opacity",d.K);else if(d instanceof w2){b="lg-"+d.D+"-"+d.G+"-"+d.F+"-"+d.H+"-"+d.o+"-"+d.A;var e=b in c.A?c.A[b]:null;if(!e){e=x2(c,"linearGradient",{x1:d.D,
y1:d.G,x2:d.F,y2:d.H,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.o;g.Da(d.C)&&(f+=";stop-opacity:"+d.C);f=x2(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.A;g.Da(d.B)&&(f+=";stop-opacity:"+d.B);d=x2(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=IBa(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},JBa=function(){},KBa=function(a,b){u2.call(this,a,b)},z2=function(){this.ub=[];
this.Pa=[];this.Me=[]},A2=function(a,b,c,d){var e=a.ee[0]-b*Math.cos(g.Pd(d))+b*Math.cos(g.Pd(d+90)),f=a.ee[1]-c*Math.sin(g.Pd(d))+c*Math.sin(g.Pd(d+90));
a.ub.push(3);a.Pa.push(1);a.Me.push(b,c,d,90,e,f);a.Xn=!1;a.ee=[e,f]},MBa=function(a,b){for(var c=a.Me,d=0,e=0,f=a.ub.length;e<f;e++){var k=a.ub[e],l=LBa[k]*a.Pa[e];
b(k,c.slice(d,d+l));d+=l}},NBa=function(a,b,c,d){y2.call(this,a,b,c,d)},B2=function(a,b){this.A=a;
this.o=b},C2=function(a,b,c,d,e){g.Bw.call(this,e);
this.width=a;this.height=b;this.B=c||null;this.M=d||null},HBa=function(a){var b=a.fk();
return b?b.width/(a.B?new g.Sd(a.B,a.M):a.fk()).width:0},OBa=function(a,b){u2.call(this,a,b)},w2=function(a,b,c,d,e,f,k,l){this.D=a;
this.G=b;this.F=c;this.H=d;this.o=e;this.A=f;this.C=g.v(k)?k:null;this.B=g.v(l)?l:null},v2=function(a,b){this.I=a;
this.K=null==b?1:b},D2=function(a,b){u2.call(this,a,b)},PBa=function(a,b,c,d){y2.call(this,a,b,c,d)},E2=function(a,b){u2.call(this,a,b)},F2=function(a,b,c,d,e){C2.call(this,a,b,c,d,e);
this.A={};this.V=g.ke&&!g.Kd(526);this.K=new g.ho(this)},x2=function(a,b,c){a=a.I.o.createElementNS("http://www.w3.org/2000/svg",b);
c&&G2(a,c);return a},G2=function(a,b){for(var c in b)a.setAttribute(c,b[c])},H2=function(a,b,c,d){b=x2(a,"path",{d:QBa(b)});
c=new PBa(b,a,c,d);a.C.sa().appendChild(c.sa())},QBa=function(a){var b=[];
MBa(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},IBa=function(a,b,c){if(b in a.A)return a.A[b];
var d="_svgdef_"+RBa++;c.setAttribute("id",d);a.A[b]=d;a.H.appendChild(c);return d},SBa=function(){I2||(I2=new g.ih(400),I2.start());
return I2},J2=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.I)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.I)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.FI(a.trackingParams));var k=(0,g.I)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},q=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=q;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.WA=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.I)(u.loggingUrls||[],c);p.Io=g.Yb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.I)(n.impressionUrls||[],c);p.XL=(0,g.I)(n.hovercardShowUrls||[],c);p.Jd={itct:n.trackingParams};p.visualElement=g.FI(n.trackingParams);if("VIDEO"==q)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Zp=!1,p.Sr=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==q)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Zp=!1,p.Sr=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==q){if(q=g.Yb(u,"browseEndpoint","browseId"))p.channelId=q,p.targetUrl="/channel/"+q;p.Zp=!1;p.Sr="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(q=n.hovercardButton)if(q=q.subscribeButtonRenderer){u=d(q.unsubscribedButtonText);var w=d(q.subscribedButtonText);if(q.subscribed){var B=d(q.subscriberCountWithUnsubscribeText);var G=d(q.subscriberCountText)}else B=d(q.subscriberCountText),
G=d(q.subscriberCountWithSubscribeText);var H=null;if(n.signinEndpoint&&(H=g.Yb(n,"signinEndpoint","webNavigationEndpointData","url"),!H)){n=void 0;break a}if(u&&(w||H)){n={subscribed:q.subscribed,subscribeText:u,subscribeCount:B,unsubscribeText:w,unsubscribeCount:G,enabled:q.enabled,signinUrl:H,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==q&&(p.targetUrl=g.Yb(u,"urlEndpoint","url"),p.Zp=!0,p.Sr="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.we)(k,function(l){return!!l});
return f},K2=function(a){g.lV.call(this,a);
this.A=null;this.K=!1;this.B=null;this.o={};this.G={};this.F=this.C=null;this.L=[];a=g.Y(a);this.M=g.WN(a)||g.YN(a);this.qG=!0;this.H=0;this.I=new g.wq(null);this.D=new g.QH(this);g.M(this,this.D);this.D.R(this.player,g.ZQ("creatorendscreen"),this.GN);this.D.R(this.player,"crx_creatorendscreen",this.HN);this.D.R(this.player,"resize",this.gD);this.D.R(window,"focus",this.FU);this.load();var b=g.pe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Rf(this,function(){g.ve(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},TBa=function(a){return a.player.getVideoData().Dc?"current":a.M?"new":"current"},L2=function(a){return"creator-endscreen-editor"===a},M2=function(a,b){g.aV(a.player,"creatorendscreen");
a.C&&(a.C.dispose(),a.C=null,a.F.dispose(),a.F=null);for(var c in a.o)a.o[c].dispose();a.o={};a.G={};0<a.L.length&&(a.L.forEach(function(l){l.dispose()}),a.L.length=0);
a.H=0;if((a.A=b)&&b.elements){UBa(a);c=[];var d=new g.XQ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.Y(a.player).A||(a.C=new g.W({J:"div",N:"ytp-ce-shadow"}),g.cV(a.player,a.C.element,4),a.F=new g.IV(a.C,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=VBa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.cV(a.player,f.element,4);var k=new g.XQ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);WBa(a,f,e)}g.YU(a.player,
c);a.gD()}},UBa=function(a){var b=g.VI(),c=g.WI();
c&&b&&a.A.visualElement&&g.HI(c,b,[a.A.visualElement],void 0)},VBa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={J:"div",da:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Io||"","aria-hidden":"true"},P:[{J:"div",N:"ytp-ce-element-shadow"},{J:"div",N:"ytp-ce-covering-image",T:N2(b)},{J:"div",N:"ytp-ce-covering-shadow-top"},{J:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{J:"div",da:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.xq(a.I,b.title||"")},ca:b.title},{J:"div",N:"ytp-ce-video-duration",ca:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={J:"div",da:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Io||"","aria-hidden":"true"},P:[{J:"div",N:"ytp-ce-element-shadow"},{J:"div",N:"ytp-ce-covering-image",T:N2(b)},{J:"div",N:"ytp-ce-covering-shadow-top"},{J:"a",N:"ytp-ce-covering-overlay",T:{href:b.targetUrl,tabindex:"-1"},P:[{J:"div",da:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],T:{dir:g.xq(a.I,b.title||"")},ca:b.title},{J:"div",N:"ytp-ce-playlist-count",P:[{J:"div",
N:"ytp-ce-playlist-icon"},{J:"div",N:"ytp-ce-playlist-count-text",ca:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={J:"div",da:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Io||"","aria-hidden":"true"},P:[{J:"div",N:"ytp-ce-element-shadow"},{J:"div",N:"ytp-ce-expanding-overlay",P:[{J:"div",N:"ytp-ce-expanding-overlay-hider"},{J:"div",N:"ytp-ce-expanding-overlay-background"},{J:"div",N:"ytp-ce-expanding-overlay-content",
P:[{J:"div",N:"ytp-ce-expanding-overlay-body",P:[{J:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{J:"a",da:["ytp-ce-channel-title","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.xq(a.I,b.title||"")},ca:b.title},b.subscribeButton?{J:"div",N:"ytp-ce-subscribe-container",P:[{J:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{J:"div",N:"ytp-ce-channel-subscribers-text",ca:b.subscribersText}:"",b.metadata?{J:"div",da:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ca:b.metadata}:""]}]}]}]},{J:"div",N:"ytp-ce-expanding-image",T:N2(b)}]};c=new g.W(c);var d=g.Zd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.S(d,"ytp-ce-subscribe-button");if(g.Y(a.player).A){var e=null;var f=b.Jd.itct}else e="endscreen",f=null;e=new g.y_(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.L.push(e)}break;case "WEBSITE":c={J:"div",da:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Io||"","aria-hidden":"true"},P:[{J:"div",N:"ytp-ce-element-shadow"},{J:"div",N:"ytp-ce-expanding-overlay",P:[{J:"div",N:"ytp-ce-expanding-overlay-hider"},{J:"div",N:"ytp-ce-expanding-overlay-background"},{J:"div",N:"ytp-ce-expanding-overlay-content",P:[{J:"div",N:"ytp-ce-expanding-overlay-body",
P:[{J:"div",N:"ytp-ce-expanding-overlay-body-padding",P:[{J:"div",N:"ytp-ce-website-title",T:{dir:g.xq(a.I,b.title||"")},ca:b.title},{J:"div",N:"ytp-ce-website-metadata",ca:b.metadata},{J:"a",da:["ytp-ce-website-goto","ytp-ce-link"],T:{href:b.targetUrl,target:"_blank",tabindex:"-1"},ca:b.callToAction}]}]}]}]},{J:"div",N:"ytp-ce-expanding-image",T:N2(b)},{J:"div",N:"ytp-ce-expanding-icon",T:XBa(b.iconUrl)}]},c=new g.W(c)}b.o&&g.S(c.element,"ytp-ce-placeholder");return c},N2=function(a){if(a.WA)var b=
a.WA.thumbnails;
return XBa(b?b[b.length-1].url:null)},XBa=function(a){return a?{style:"background-image: url("+a+")"}:{}},WBa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.X("mouseenter",(0,g.C)(a.ew,a,b,c));b.X("mouseleave",(0,g.C)(a.Sw,a,b,c));g.Y(a.player).A||b.X("click",(0,g.C)(function(l){g.S(l.element,"ytp-ce-element-hover")},a,b));
b.X("click",(0,g.C)(a.yE,a,c));b.X("keypress",(0,g.C)(a.yE,a,c));b.X("focus",(0,g.C)(function(l,m){this.ew(l,m)},a,b,c));
b.X("blur",(0,g.C)(function(l,m){this.Sw(l,m)},a,b,c));
b.X("touchstart",(0,g.C)(a.ew,a,b,c));var f=g.ce("ytp-ce-expanding-overlay-hider",b.element);f&&b.R(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Pr(b.element,"ytp-ce-element-hover");g.Pr(b.element,"ytp-ce-force-expand")});
b.X("keydown",(0,g.C)(function(l,m){this.qG=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.C)(function(l,m,n){this.H+=n;0<this.H?(g.S(l.element,"ytp-ce-force-expand"),O2(this,m.id,!0)):(g.Pr(l.element,"ytp-ce-force-expand"),g.Pr(l.element,"ytp-ce-element-hover"),O2(this,m.id,!1))},a,b,c);
a=(0,g.C)(function(l,m){m&&(l.X("blur",function(){g.zi(m)&&this.qG&&m.focus()}),l.R(m,"focus",d),l.R(m,"blur",e))},a,b);
a(g.ce("ytp-sb-subscribe",b.element));a(g.ce("ytp-sb-unsubscribe",b.element));b.X("focus",d);b.X("blur",e)},O2=function(a,b,c){a.C&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.T(a.o[d].element,"ytp-ce-element-shadow-show",c)},P2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||L2(g.Y(a.player).playerStyle))c&&c();else{b=YBa(a,b);var e=0,f=!1,k=new g.V(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.WG(b[a],d)}},Q2=function(a,b,c){P2(a,b.clickUrls,c);
(a=g.WI())&&b.Zp&&g.JI(a,b.visualElement)},YBa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(ZBa(b[e],c));return d},ZBa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},R2=function(a){return g.Ha(a)&&a.length?a[0]:a},S2=function(a){var b=/.+/;
return g.x(a)&&null!=b&&null!=a&&a.match(b)?a:""},T2=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},U2=function(a){return g.x(a)?a:""},V2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},W2=function(a,b){return"true"==a||"false"==a?"true"==a:b},X2=function(a,b){return g.x(a)?parseFloat(a):b},Y2=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Md(a,b,c);if(a>=b&&a<=c)return a}return e},$Ba=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.E)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},Z2=function(a,b){if(null==a)return null;
if(g.Ia(a)){var c=[];(0,g.E)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},aCa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.Oh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},bCa=function(a){function b(c){return(0,g.we)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},cCa=function(a){this.externalId=a},dCa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},$2=function(a){if(!a)return null;
var b=g.Oc(U2(a.value));b=g.Lc(b);if(!b)return null;var c=V2(a.target,eCa,"current");return null==c?null:new dCa(b,c,W2(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},a3=function(a){return a.value?a.value:null},fCa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},iCa=function(a){if(!a)return null;
var b=V2(a.type,gCa),c=V2(a.trigger,hCa),d=R2(a.url);d=$2(d?d:null);a=R2(a.subscribeData);var e=a?a:null;e?(a=U2(e.external_user_id),e=U2(e.subscription_token),a=a&&e?new cCa(a):null):a=null;return b?new fCa(b,c,d,a):null},jCa=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},b3=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},c3=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Bl=c;this.C=d;this.t=e;this.D=f;this.F=k;this.G=l;this.B=m;this.A=n;this.o=p},lCa=function(a,b){if(!a)return null;
var c=X2(a.x,0),d=X2(a.y,0),e=X2(a.w,0),f=X2(a.h,0),k=$Ba(a.t),l=X2(a.d,0),m=X2(a.px,0),n=X2(a.py,0),p=X2(a.scaleSlope,1),q=X2(a.scaleSlopeX,p);p=X2(a.scaleSlopeY,p);var u=V2(a.scaleDimension,kCa,"xy");return b(c,d,e,f,k,l,m,n,q,p,u)},d3=function(a,b){var c=mCa(b,nCa(a,new g.Rh(a.x,a.y,a.Bl,a.C),b.o)),d=b.o,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Md(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Md(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},nCa=function(a,b,c){var d=a.F,e=a.G,f=a.o?a.o:"xy",k=jCa(c,a.B,f);
a=b3(c,a.A,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.Rh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},oCa=function(a){return a?lCa(a,function(b,c,d,e,f,k,l,m,n,p,q){return new c3(b,c,d,e,f,k,l,m,n,p,q)}):null},pCa=function(a,b){this.o=a;
this.A=b||null},mCa=function(a,b){var c=a.A?d3(a.A,new pCa(a.o)):a.o;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Qd?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Da(c)&&(d.top+=c));return d},qCa=function(a,b,c,d,e,f,k,l,m,n,p,q,u){c3.call(this,a,b,c,d,e,l,m,n,p,q,u);
this.H=f;this.I=k},rCa=function(a){if(!a)return null;
var b=X2(a.sx,0),c=X2(a.sy,0);return lCa(a,function(d,e,f,k,l,m,n,p,q,u,w){return new qCa(d,e,f,k,l,b,c,m,n,p,q,u,w)})},sCa=function(a,b,c,d,e,f,k,l,m,n,p,q,u,w){this.A=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.o=e;this.F=f;this.C=k;this.textAlign=l;this.textSize=m;this.B=n;this.padding=p;this.effects=q;this.cornerRadius=u;this.D=w},uCa=function(a){if(!a)return null;
var b=T2(a.fgColor,"#1A1A1A"),c=T2(a.bgColor,"#FFF"),d=T2(a.borderColor,"#000"),e=Y2(a.borderWidth,0,5,!1,0),f=Y2(a.bgAlpha,0,1,!1,.8),k=T2(a.highlightFontColor,"#F2F2F2"),l=Y2(a.highlightWidth,0,5,!1,3),m=U2(a.textAlign),n=Y2(a.textSize,3.3,30.1,!0,3.6107),p=U2(a.fontWeight),q=aCa(a.padding),u=bCa(a.effects),w=Y2(a.cornerRadius,0,10,!0,0);a=R2(a.gradient);if(a=a?a:null){var B=Y2(a.x1,0,100,!0,0),G=Y2(a.y1,0,100,!0,0),H=Y2(a.x2,0,100,!0,100),U=Y2(a.y2,0,100,!0,100),ka=T2(a.color1,"#FFF"),ra=T2(a.color2,
"#000");a=new tCa(B,G,H,U,ka,ra,Y2(a.opacity1,0,100,!0,100),Y2(a.opacity2,0,100,!0,0))}else a=null;return new sCa(b,c,d,e,f,k,l,m,n,p,q,u,w,a)},tCa=function(a,b,c,d,e,f,k,l){this.C=a;
this.D=b;this.B=c;this.F=d;this.o=e;this.A=f;this.G=k;this.H=l},vCa=function(a,b,c,d){this.type=a;
this.A=b;this.o=c;this.C=d},xCa=function(a){if(!a)return null;
var b=V2(a.type,wCa,"rect"),c=Z2(a.rectRegion,oCa),d=Z2(a.anchoredRegion,rCa);a=Z2(a.shapelessRegion,oCa);return new vCa(b,c,d,a)},yCa=function(a){return a.A&&a.A.length?a.A[0]:a.o&&a.o.length?a.o[0]:a.C&&a.C.length?a.C[0]:null},zCa=function(a,b){this.A=a;
this.o=b},ACa=function(a,b){this.state=a;
this.ref=b},CCa=function(a){if(!a)return null;
var b=V2(a.state,BCa);a=S2(a.ref);return b?new ACa(b,a):null},DCa=function(a,b,c,d){this.o=a||[];
this.C=b||[];this.B=c;this.A=d;this.value=!1},ECa=function(a){if(!a)return null;
var b=Z2(a.condition,CCa),c=Z2(a.notCondition,CCa),d=W2(a.show_delay,!1);a=W2(a.hide_delay,!1);return b||c?new DCa(b,c,d,a):null},FCa=function(a,b,c){(0,g.E)(a.o,g.Na(b,!1),c);
(0,g.E)(a.C,g.Na(b,!0),c)},e3=function(a,b,c,d,e,f,k,l,m,n,p,q,u,w){this.id=a;
this.author=b;this.type=c;this.style=d;this.B=e;this.segment=f;this.C=k||[];this.G=l||[];this.A=m;this.F=n;this.D=p;this.data=q;this.o=u;this.itct=w},ICa=function(a){if(!a)return null;
var b=S2(a.id),c=S2(a.author),d=V2(a.type,GCa),e=V2(a.style,f3),f=U2(R2(a.TEXT)),k=U2(a.data);k=0!=k.length?JSON.parse(k):{};var l=R2(a.segment);var m=l?l:null;m?(S2(m.timeRelative),l=S2(m.spaceRelative),l=(m=Z2(m.movingRegion,xCa))?new zCa(l,m):null):l=null;m=Z2(a.action,iCa);var n=Z2(a.trigger,ECa),p=R2(a.appearance);(p=uCa(p?p:null))||(p=uCa({}));var q=V2(a.coordinate_system,HCa,"video_relative"),u=W2(a.closeable,!0),w=U2(a.log_data);a=U2(a.itct);return b&&d?new e3(b,c,d,e,f,l,m,n,p,q,u,k,w,a):
null},h3=function(a){return g3(a,function(b){return"click"==b.trigger})},g3=function(a,b){return(0,g.Ik)(a.C,b,void 0)},JCa=function(a,b,c){(0,g.E)(a.C,b,c)},MCa=function(a,b){return g.Ua(a.C,b,void 0)},gDa=function(a,b,c){(0,g.E)(a.G,b,c)},hDa=function(a,b){(0,g.I)(a.G,b,void 0)},i3=function(a){return(a=iDa(a))?yCa(a):null},iDa=function(a){a.segment?(a=a.segment,a=a.o.length?a.o[0]:null):a=null;
return a},jDa=function(a,b){var c=i3(a);
return c&&b?b3(b,c.A,c.o?c.o:"xy"):1},lDa=function(a,b,c){this.o={};
this.C=!1;this.D="ivTrigger:"+a;this.A=c;FCa(b,function(d,e){var f=kDa(e.state,e.ref);this.A.subscribe(f,(0,g.C)(this.B,this,f,d));this.o[f]=d},this)},kDa=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},j3=function(){this.o=!1;
this.D=this.A=null},k3=function(a,b,c){a.A?(a.A.setSize(b,c),a.A.clear()):(b=new F2(b,c,void 0,void 0,void 0),a.A=b,a.A.Lp(),a.D=g.ne("DIV"),b=a.A.sa(),a.D.appendChild(b));
return a.A},l3=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Pb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},m3=function(a,b){var c=":"+(g.Aw.getInstance().o++).toString(36);
b.setAttribute("result",c);a.appendChild(b);return c},mDa=function(a,b){var c=m3(a,l3("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=m3(a,l3("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},l3("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=m3(a,l3("feComposite",{"in":c,in2:b,operator:"in"}));return m3(a,l3("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},nDa=function(a,b){var c=m3(a,l3("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=m3(a,l3("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=m3(a,l3("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=m3(a,l3("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=m3(a,l3("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=m3(a,l3("feComposite",{operator:"out","in":c,in2:d}));return m3(a,l3("feComposite",{operator:"over","in":b,in2:c}))},oDa=function(a,b){return b},pDa=function(a){var b=
l3("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.E)(a,function(d){a:{switch(d){case "bevel":d=mDa;break a;case "dropshadow":d=nDa;break a}d=oDa}c=d(b,c)});
return b},qDa=function(a){a=(0,g.we)(a,function(b){return b in n3});
g.tb(a,function(b,c){return n3[b]-n3[c]});
return a},rDa=function(a){return g.Ua(a,function(b){return"dropshadow"==b})?new g.Oh(0,7,7,0):new g.Oh(0,0,0,0)},sDa=function(a,b,c){var d=new z2;
d.moveTo(a.left+b+c,a.top+c);d.Mc(a.left+a.width-b-c,a.top+c);A2(d,b,b,-90);d.Mc(a.left+a.width-c,a.top+a.height-b-c);A2(d,b,b,0);d.Mc(a.left+b+c,a.top+a.height-c);A2(d,b,b,90);d.Mc(a.left+c,a.top+b+c);A2(d,b,b,180);d.close();return d},tDa=function(a,b,c,d){var e=a.D;
e?a=new w2(e.C*b/100,e.D*c/100,e.B*b/100,e.F*c/100,e.o,e.A,e.G,e.H):(b=a.o,a=new v2(a.bgColor,d?Math.max(b,.9):b));return a},o3=function(a,b){var c=g.Sh(a);
c.expand(rDa(b));return new g.Rh(c.left,c.top,c.right-c.left,c.bottom-c.top)},uDa=function(a,b,c){if(c.length&&(b=g.Zd(document,"g",void 0,b),b.length)){var d=qDa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.A?a.A[c]:null;e?a=e:(d=pDa(d),a=0<d.childNodes.length?IBa(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},p3=function(){j3.call(this);
this.B=0},vDa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},q3=function(a){j3.apply(this,arguments)},r3=function(a){j3.apply(this,arguments)},s3=function(a){p3.apply(this,arguments)},t3=function(a,b,c,d,e){g.L.call(this);
this.o=a;this.Y=b;this.F=c;this.ea=d;this.ga=e;this.I=!1;this.Z=new g.NH(this);g.M(this,this.Z);this.V=this.D=this.G=this.M=this.A=null;this.aa=!1;this.ba=this.K=this.L=null;this.Oq=new g.vm(this.oL,100,this);g.M(this,this.Oq);this.H=new g.V(this.cC,500,this);g.M(this,this.H);this.O=this.C=this.B=null},wDa=function(a,b){var c=(0,g.C)(function(d,e,f){e=f?u3(this,e,(0,g.C)(f,this)):u3(this,e);
this.Z.X(b,d,e)},a);
c("mouseover","G",a.oD);c("mouseout","F",a.ci);c("click","D");c("touchend","D")},xDa=function(a){if(a.o.D){if(g3(a.o,function(d){return"close"==d.type}))var b=a.A;
else a.B=g.ne("DIV","annotation-close-button"),g.N(a.B,!1),g.BF(a.B,"annotation_id",a.o.id),a.A.appendChild(a.B),b=a.B;var c=function(d){d.stopPropagation()};
a.Z.X(b,"click",u3(a,"E",c));a.Z.X(b,"touchend",u3(a,"E",c))}},u3=function(a,b,c){return(0,g.C)(function(d){if(this.ga)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.N(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.Le(f,"annotation")){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.N(e,
!0)}}e=g.xi(d.target);d=new g.Qd(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.ea.U(b,this.o)},a)},w3=function(a){if(a.A||a.C){var b=i3(a.o);
if(b){var c=v3(a);if(a.A){b=d3(b,c);var d=g.PU(a.F).getVideoContentRect();g.vi(a.A,b.width,b.height);g.ki(a.A,b.left,b.top);a.M=new g.Rh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=i3(a.o))&&d?jCa(d,e.B,e.o?e.o:"xy"):1;var f=jDa(a.o,d);d=a.o.A;d.padding?d=d.padding:(d="speech"==a.o.style?1.6:.8,d=new g.Oh(d,d,d,d));d=new g.Oh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.D&&(d.right+=1.5*c.o.height/100);a.A.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+
d.left+"px";"label"==a.o.style&&a.G&&(a.G.style.padding=a.A.style.padding);d=c.o;var k=!1,l=0,m=0;var n=g.PU(a.F).getVideoContentRect();var p=g.WU(a.F);g.Th(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.o.F&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.D){f=yDa(a,23,b,d,e);if(a.B){var q=43-f.width;0<q&&(b.left+f.left-q>n.left&&(f.left-=q),f.width+=q)}q=f;g.vi(a.D,f.width,f.height);g.ki(a.D,f.left,f.top)}a.B&&
(q?b=new g.Qd(q.left+q.width-23-18,a.aa?q.top+2:q.top+q.height-18-2):(q=yDa(a,18,b,d,e),b=new g.Qd(q.left,q.top),g.vi(a.B,q.width,q.height)),g.ki(a.B,b));a.V=new g.Rh(a.M.left+q.left,a.M.top+q.top,q.width,q.height);a.L=a.Z.X(g.PU(a.F),"mousemove",a.wO,a)}else a.D&&(q=e/f*d.height*4.2/100,q=new g.Sd(q,q),"highlight"==a.o.type||"label"==a.o.style?(e=1.5*d.height/100,q=new g.Rh(b.width-q.width-e,b.height-q.height-e,q.width,q.height)):q=new g.Rh(b.width-q.width-3*d.height/100,(b.height-q.height)/2,q.width,
q.height),g.vi(a.D,q.width,q.height),g.ki(a.D,q.left,q.top)),a.B&&(q=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.ki(a.B,q&&e?new g.Qd(b.width-9,-9):q?new g.Qd(b.width-9,45<b.height?9:b.height-9):e?new g.Qd(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Qd(45<b.width?b.width-9-18:-9,b.height-9):new g.Qd(-9,45<b.height?9:b.height-9)))}a.C&&a.C.C(a.o,c);if(a.A){c=a.A;b=a.o.A;c.style.color="highlightText"==a.o.style?b.F:b.A;q=g.PU(a.F).getVideoContentRect();c.style.fontSize=
360*b.textSize*jDa(a.o,q)/100+"px";q=a.o.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==q||"highlightText"==q?"center":"left";b.B&&(c.style.fontWeight=b.B);a=a.A;c=a.style.overflow;q=(b=g.ce("annotation-link-icon",a))?g.zi(b):!1;e=(d=g.ce("annotation-close-button",a))?g.zi(d):!1;q&&g.N(b,!1);e&&g.N(d,!1);m=f="";if(n=g.ce("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>
a.offsetWidth){l=k=yBa(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.N(d,!0);q&&g.N(b,!0)}}}},yDa=function(a,b,c,d,e){var f=0<e;
b=new g.Rh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.S(a.A,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.S(a.A,"annotation-extend-up"),a.aa=!0);return b},x3=function(a){return"label"!=a.o.style||a.C.o},v3=function(a){var b=g.PU(a.F).getVideoContentRect();
if("player_relative"==a.o.F){var c=g.PU(a.F).getPlayerSize();b=new g.Rh(-b.left,-b.top,c.width,c.height)}else b=new g.Rh(0,0,b.width,b.height);return new pCa(b,a.O?i3(a.O):null)},zDa=function(a,b){return b?new g.Rh(a.x+b.left,a.y+b.top,b.width,b.height):null},y3=function(a,b,c){g.L.call(this);
this.A=a;this.annotation=b;this.view=c;this.o=null;this.C=this.isVisible=!1;ADa(b,a)},ADa=function(a,b){hDa(a,function(c){return new lDa(a.id,c,b)})},BDa=function(a){a.A.unsubscribe("resize",a.nD,a);
a.A.unsubscribe("onVideoAreaChange",a.dF,a)},z3=function(a){a.o&&(a.o.stop(),a.o=null)},CDa=function(a,b,c){t2.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.B=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=$2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},A3=function(a,b,c){t2.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.B=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=$2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.o=null;if(a=b.signin_url)this.o=$2({target:"current",value:a});this.L=b.signin_title||null;this.K=b.signin_message||null},DDa=function(a,b,c){A3.call(this,a,b,c);
this.I=b.ypc_flow_type;this.G=b.innertube_request_params},EDa=function(a,b,c){t2.call(this,a,b,c);
this.B=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=$2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},FDa=function(a,b,c){t2.call(this,a,b,c);
this.G=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.o=b.hasOwnProperty("old_vote")?b.old_vote:null;this.B=null;if(a=b.signin_url)this.B=$2({target:"current",value:a});this.I=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},HDa=function(a,b,c){A3.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new GDa(a[b]))},GDa=function(a){this.merchant=g.J(a.merchant);
this.price=g.J(a.price)},IDa=function(a,b,c){A3.call(this,a,b,c);
this.M=b.ypc_item_type;this.I=b.ypc_item_id;this.G=b.ypc_flow_type},JDa=function(a,b,c){t2.call(this,a,b,c);
this.B=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=$2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},B3=function(a,b,c){t2.call(this,a,b,c);
this.I=b.image_url;this.B=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.G=!!b.is_paygated;this.K=!!b.user_has_entitlement;this.url=$2({target:b.target||"new",value:b.url})},KDa=function(a){this.o=a;
this.A={}},LDa=function(a){var b={};
b=(b["iv-event"]=1,b);g.VU(a.o,"iv",b,void 0)},F3=function(a,b,c,d){if(b){var e=C3(a,b);
a.A[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=D3(a,"cta_annotation_shown",e,c);E3(a,e,MDa(b,d))}},G3=function(a,b,c,d,e,f){if(b){var k=C3(a,b);
k["iv-event"]=3;k["i-time"]=a.A[b]||"";d&&g.lc(k,d);b=D3(a,"cta_annotation_clicked",k,e);E3(a,k,b,c,f)}},H3=function(a,b){if(b){var c=C3(a,b);
c["iv-event"]=4;c["i-time"]=a.A[b]||"";var d=D3(a,"cta_annotation_closed",c);E3(a,c,d)}},MDa=function(a,b){return b?(0,g.I)(a,g.Na(function(c,d){return g.po(d,c)},b)):a},D3=function(a,b,c,d){d=d?g.jb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Y(a.o).experiments.o("enable_async_click_tracking")){a:{c=c["a-id"];a=a.o.getVideoData();if(a.fA){if((b=a.fA[b])&&g.UK(b)){a=g.qd("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.jr){b=g.kG(a.jr,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},E3=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.E)(c||[],function(n){f++;
g.WG(n,m)});
e&&(f++,0!=e&&a.o.sendVideoStatsEngageEvent(e,m));g.VU(a.o,"iv",b,m)},C3=function(a,b){var c={};
if(b){var d=new g.Yn(b);(0,g.E)(d.Gb(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.o.getCurrentTime().toFixed(2);
c.ps=g.Y(a.o).playerStyle;return c},I3=function(a,b,c,d,e){e=C3(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;E3(a,e,d)},J3=function(a,b,c,d){c&&(c=C3(a,c),c["iv-event"]=b,E3(a,c,d))},NDa=function(a,b,c,d,e,f,k){this.A=a;
this.B=b;this.D=c;this.videoData=d;this.logger=e;this.o=f;this.C=k},K3=function(a,b,c){this.o=a;
this.B=b;this.D=c;this.A=new g.wq(null)},PDa=function(a,b){var c=[];
(0,g.E)(b.choices,function(k){c.push({J:"li",N:b.G+"-"+k.index.toString(),P:[{J:"label",P:[{J:"input",N:"iv-card-poll-choice-input",T:{type:"checkbox",role:"radio",name:b.G+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{J:"span",N:"iv-card-poll-choice-text",P:[{J:"span",N:"iv-card-poll-choice-percent"},L3(this,"span",void 0,k.desc)]}]},{J:"div",N:"iv-card-poll-result",P:[{J:"div",N:"iv-card-poll-result-bar"}]}]})},a);
var d={J:"ul",T:{role:"radiogroup"},P:c},e={};b.B&&(e["aria-label"]=g.vV("$POLL_TITLE - Inicia sesi\u00f3n para votar.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{J:"div",N:"iv-card-content",P:[L3(a,"h2",e,b.title),{J:"form",P:[{J:"fieldset",P:[d]}]}]}];b.B&&(f.push("iv-card-unavailable"),d.push({J:"div",da:["iv-card-sign-in"],P:[{J:"h2",ca:"\u00bfTe gustar\u00eda votar?"},{J:"a",da:["iv-card-sign-in-button","iv-button"],T:{href:a3(b.B)},P:[{J:"span",da:["iv-button-content"],ca:"Iniciar sesi\u00f3n"}]}]}));
f=new g.W({J:"div",da:f,P:d});d=f.element;ODa(b,d);tBa(a.o.A,d,g.Na(a.G,b),a);(0,g.E)(g.$d("iv-card-poll-choice-input",d),function(k){this.o.A.X(k,"focus",g.Na(this.C,!0));this.o.A.X(k,"blur",g.Na(this.C,!1))},a);
b.B&&(d=g.ce("iv-card-sign-in-button",d),a.B(d,b.B,b.id,b.Jd,b.C,b.A.click,5));return f},O3=function(a,b,c,d){var e=b.displayDomain?{J:"div",
N:"iv-card-image-text",ca:b.displayDomain}:"",f=QDa(a,b),k=["iv-card"];b.o&&k.push("iv-card-unavailable");e=[{J:"a",N:"iv-click-target",T:{href:a3(b.url)},P:[M3(b.imageUrl,e),{J:"div",N:"iv-card-content",P:[L3(a,"h2",void 0,b.title),f]}]}];b.o&&e.push({J:"div",da:["iv-card-sign-in"],P:[L3(a,"h2",void 0,b.L||""),{J:"p",ca:b.K},{J:"a",da:["iv-card-sign-in-button","iv-button"],T:{href:a3(b.o)},P:[L3(a,"span","iv-button-content","Iniciar sesi\u00f3n")]}]});k=new g.W({J:"div",da:k,P:e});N3(a,k,b,c,d);
return k},RDa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.K?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.G&&b.B?{J:"span",da:d,T:e,ca:b.B}:"";c={J:"div",da:["iv-card",c],P:[{J:"a",N:"iv-click-target",T:{href:a3(b.url)},P:[M3(b.I,d?{J:"div",N:"iv-card-image-text",P:[d,b.priceText]}:""),{J:"div",N:"iv-card-content",P:[{J:"h2",N:"iv-card-primary-link",ca:b.title},P3(a,b)]}]}]};c=new g.W(c);N3(a,c,b);return c},Q3=function(a,b){return b.customMessage?L3(a,"div",
"iv-card-message",b.customMessage):""},M3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{J:"div",N:"iv-card-image",T:{style:c},P:d}},P3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.E)(b.metaInfo,function(d){c.push(L3(this,"li","",d))},a);
return{J:"ul",N:"iv-card-meta-info",P:c}},L3=function(a,b,c,d){c?g.x(c)?c={"class":c}:g.Ha(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.xq(a.A,d);return{J:b,T:c,ca:d}},QDa=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.B&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.B+");");d.dir=g.xq(a.A,b.customMessage);var e=[{J:"span",ca:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({J:"span",N:"iv-card-link-icon"}));return{J:"div",da:c,T:d,P:e}},ODa=function(a,b){var c=0;
(0,g.E)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.ce(a.G+"-"+e.index.toString(),b);e=e.count/c;null==a.o&&(e=0);g.T(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.o==d);f.getElementsByTagName("input")[0].checked=a.o==d;var k=Math.floor(100*e).toFixed(0),l=g.ce("iv-card-poll-choice-percent",f);g.De(l,g.vV("$PERCENT%",{PERCENT:k}));f=g.ce("iv-card-poll-result-bar",f);g.ci(f,"transform","scaleX("+e.toFixed(2)+")")}g.T(b,"iv-card-poll-voted",null!=a.o);g.T(b,"iv-card-poll-expanded",
null!=a.o&&1<a.choices.length)},SDa=function(a,b,c,d){d?(c&&a.o.videoData.Da||a.o.o.pauseVideo(),a.o.o.isFullscreen()&&a.o.o.toggleFullscreen(),G3(a.o.logger,b.C,d,void 0,b.A.click,5),(a=g.WI())&&g.JI(a,b.F)):b.url&&a.D(b.url,b.id,b.Jd,b.C,b.A.click||[],5)},N3=function(a,b,c,d,e){c.o&&TDa(a,g.$d("iv-card-sign-in-button",b.element),c,c.o,e);
c.url&&TDa(a,g.$d("iv-click-target",b.element),c,c.url,d)},TDa=function(a,b,c,d,e){(0,g.E)(b,function(f){if(e){var k=(0,g.C)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.o.A.X(f,"click",k)}else d&&this.B(f,d,c.id,c.Jd,c.C,c.A.click,5)},a)},UDa=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},R3=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=VDa(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},VDa=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},WDa=function(a){a=a3(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!R3(a))||(b=g.vh(g.uh(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.iG(a);if(!b||!b.v)return null;if(b=b.t)return UDa(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.gG(a[1]))&&a.t?UDa(a.t):-1},XDa=function(a){a=a3(a);
a=a.replace(/https?:\/\//g,"");return R3(a)?(a=g.iG(a))&&a.v?a.v:null:null},YDa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},S3=function(a,b){return b?b:R3(a)?"current":"new"},T3=function(a,b){g.L.call(this);
this.Ea=a;this.context=b;this.Dy=!1;this.ea=0},ZDa=function(a){return(0,g.K)()-a.ea},$Da=function(a,b,c,d,e,f){var k=a3(b);
if(k){var l=S3(k,b.target),m=(0,g.C)(function(){b.o&&this.context.o.pauseVideo();var p=this.context.videoData.Dc||!1,q=g.iG(k||"");p&&q&&(q.v||q.list)?g.O0(this.context.o.app,q.v,c,q.list,!1,void 0,void 0):g.tV(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=ZDa(a);G3(a.context.logger,d,m,n,e,f);R3(k)||(a=g.WI(),d=c.itct,a&&d&&g.JI(a,g.FI(d)))}},W3=function(a,b,c){T3.call(this,b,c);
var d=this;this.A=a;this.Y=null;this.aa=this.xa=this.D=this.ya=!1;this.ba=null;this.V=new g.V(g.A,c.D.td?4E3:3E3);g.M(this,this.V);this.ma=new g.V(g.A);g.M(this,this.ma);this.F=new K3(c,(0,g.C)(this.ol,this),(0,g.C)(this.kq,this));this.I=new g.W({J:"div",N:"iv-drawer",T:{id:"iv-drawer"},P:[{J:"div",N:"iv-drawer-header",T:{"aria-role":"heading"},P:[{J:"span",N:"iv-drawer-header-text"},{J:"button",da:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Ocultar tarjetas",tabindex:"0"}}]},{J:"div",
N:"iv-drawer-content"}]});g.M(this,this.I);this.G=this.I.element;this.ha=new g.IV(this.I,330);g.M(this,this.ha);this.za=g.ce("iv-drawer-header-text",this.G);this.B=g.ce("iv-drawer-content",this.G);this.C=[];this.ua=this.O=this.H=this.ga=this.o=null;this.L=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&U3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.D)&&V3(d)});
this.M=this.K=this.ia=null},fEa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&aEa[c]){c=new aEa[c](b.id,b.data,b.o);if(!a.ya){g.Or(a.sa(),["html5-stop-propagation","iv-drawer-manager"]);g.cV(a.A,a.G,5);bEa(a);a.O=g.ce("ytp-cards-button",a.A.getRootNode());var d=g.ce("iv-drawer-close-button",a.G);a.ua=d;a.ya=!0}cEa(a,c.id);var e=dEa(a,c);if(e){d={kc:c,Qt:e.element,LC:!1};var f=eEa(a,d);g.nb(a.C,f,0,d);e.A(a.B,f);a.Uo();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Na(a.zV,d)):(e=1E3*a.context.o.getCurrentTime(),5E3>e&&e>c.startMs&&a.VF(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Na(a.VF,d)),X3(a))}}},gEa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){U3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){V3(a)});
var c=b.data.headerText;g.De(a.za,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.Y=b.data.eventId);a.ia=g.FI(b.data.trackingParams);a.M=g.FI(b.data.closeTrackingParams);a.K=g.FI(b.data.iconTrackingParams)},cEa=function(a,b){var c=hEa(a,b);
c&&(c==a.o&&(a.o=null),a.A.removeCueRange(c.kc.id),g.ve(c.Qt),g.eb(a.C,c),a.Uo(),X3(a))},U3=function(a,b,c,d){if(!a.D){a.ha.show();
a.ga=new g.V(function(){g.S(a.context.o.getRootNode(),"ytp-iv-drawer-open")},0);
a.ga.start();a.ba=g.CH(a.B,"mousewheel",(0,g.C)(a.YN,a));a.D=!0;a.ea=(0,g.K)();I3(a.context.logger,a.Y,7,void 0,d&&d.kc?d.kc.C:void 0);var e=g.WI();e&&a.ia&&a.M&&r2(e,[a.ia,a.M]);var f={TRIGGER_TYPE:b};(0,g.E)(a.C,function(k){k.LC||(k.LC=!0,F3(a.context.logger,k.kc.C,k.kc.A.KM,f));e&&r2(e,[k.kc.F])});
j2(a.A);c&&(a.H=new g.V(function(){a.ka=a.O;a.ua.focus()},330),a.H.start())}},V3=function(a){a.D&&(a.ha.hide(),g.DH(a.ba),a.ba=null,g.Pr(a.context.o.getRootNode(),"ytp-iv-drawer-open"),a.D=!1,j2(a.A),a.H&&a.H.stop(),a.H=new g.V(function(){a.ka&&(a.ka.focus(),a.ka=null)},330),a.H.start())},bEa=function(a){var b=g.ce("iv-drawer-close-button",a.G);
a.context.A.X(b,"click",a.eK,a);a.context.A.X(a.B,"touchend",function(){a.V.start()});
a.context.A.X(a.B,"scroll",a.pK,a);a.context.C.subscribe("onHideControls",function(){a.aa=!0});
a.context.C.subscribe("onShowControls",function(){a.aa=!1});
a.context.C.subscribe("onVideoAreaChange",function(){a.aa=g.Nr(a.A.getRootNode(),"ytp-autohide")});
a.L.push(g.LF("iv-button-shown",a.fN,a));a.L.push(g.LF("iv-button-hidden",a.eN,a));a.L.push(g.LF("iv-teaser-shown",a.iN,a));a.L.push(g.LF("iv-teaser-hidden",a.hN,a));a.L.push(g.LF("iv-teaser-clicked",a.gN,a))},dEa=function(a,b){switch(b.type){case "simple":return O3(a.F,b);
case "collaborator":var c=a.F,d={J:"div",da:["iv-card","iv-card-channel"],P:[{J:"a",da:["iv-click-target"],T:{href:a3(b.url),"data-ytid":b.channelId},P:[M3(b.B),{J:"div",N:"iv-card-content",P:[Q3(c,b),{J:"h2",N:"iv-card-primary-link",ca:b.title},P3(c,b)]}]}]};d=new g.W(d);N3(c,d,b);return d;case "donation":return c=a.F,d=(0,g.C)(c.F,c,b),O3(c,b,d,d);case "episode":return RDa(a.F,b,"iv-card-episode");case "movie":return RDa(a.F,b,"iv-card-movie");case "playlist":return c=a.F,d={J:"div",da:["iv-card",
"iv-card-playlist"],P:[{J:"a",N:"iv-click-target",T:{href:a3(b.url)},P:[M3(b.B,{J:"div",N:"iv-card-image-overlay",P:[{J:"span",N:"iv-card-playlist-video-count",ca:b.playlistVideoCount.toString()}]}),{J:"div",N:"iv-card-content",P:[Q3(c,b),L3(c,"h2","iv-card-primary-link",b.title),P3(c,b)]}]}]},d=new g.W(d),N3(c,d,b),d;case "poll":return PDa(a.F,b);case "productListing":c=a.F;var e=!g.ab(b.offers);d=["iv-card"];var f="",k=QDa(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({J:"div",N:"iv-card-offer-price",ca:e.price}),e.merchant&&k.push({J:"div",N:"iv-card-offer-merchant",ca:e.merchant}),k={J:"div",P:k});d={J:"div",da:d,T:{tabindex:"0"},P:[{J:"a",da:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+b.imageUrl+");",href:a3(b.url),"aria-hidden":"true",tabindex:"-1"}},{J:"div",N:"iv-card-content",P:[b.sponsored?{J:"div",N:"iv-card-sponsored",P:["Patrocinado",{J:"div",N:"iv-ad-info-container",P:[{J:"div",N:"iv-ad-info",ca:"{{adInfo}}"},
{J:"div",N:"iv-ad-info-icon-container",P:[{J:"div",N:"iv-ad-info-icon"},{J:"div",N:"iv-ad-info-callout"}]}]}]}:"",{J:"a",N:"iv-click-target",T:{href:a3(b.url)},P:[L3(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.pe("span");g.De(f,"Est\u00e1s viendo este producto porque creemos que es relevante para el v\u00eddeo. Es posible que Google reciba una compensaci\u00f3n de parte del comerciante.");d.Nb(f,"adInfo");N3(c,d,b);return d;case "tip":return c=a.F,d=(0,g.C)(c.H,c,b),O3(c,b,d,d);case "video":return c=
a.F,d=b.isLiveNow?{J:"span",da:["yt-badge","yt-badge-live"],ca:"EN DIRECTO AHORA"}:"",d={J:"div",da:["iv-card","iv-card-video"],P:[{J:"a",N:"iv-click-target",T:{href:a3(b.url)},P:[M3(b.B,b.videoDuration?{J:"span",N:"iv-card-video-duration",ca:b.videoDuration}:""),{J:"div",N:"iv-card-content",P:[Q3(c,b),L3(c,"h2","iv-card-primary-link",b.title),P3(c,b),d]}]}]},d=new g.W(d),N3(c,d,b),d}return null},eEa=function(a,b){if(0==a.C.length)return 0;
var c=g.Wa(a.C,function(d){return b.kc.startMs>d.kc.startMs||b.kc.startMs==d.kc.startMs&&b.kc.timestamp>=d.kc.timestamp?!0:!1});
return-1==c?0:c+1},iEa=function(a){return a.o?"productListing"==a.o.kc.type:(0,g.bk)(a.C,function(b){return"productListing"==b.kc.type})},X3=function(a){g.T(a.A.getRootNode(),"ytp-cards-shopping-active",iEa(a))},jEa=function(a,b){if(a.I.C){var c=new o2([0,
a.B.scrollTop],[0,b.Qt.offsetTop],600,GBa);a.context.B.X(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.B.X(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.WP(a.I,!0),a.B.scrollTop=b.Qt.offsetTop,g.WP(a.I,!1)},Y3=function(a){return a.o&&a.o.kc?a.o.kc:a.C[0]&&a.C[0].kc?a.C[0].kc:null},hEa=function(a,b){return g.Ua(a.C,function(c){return c.kc.id==b})},Z3=function(a,b,c){T3.call(this,a,b);
this.annotation=c;this.isActive=!1},kEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},$3=function(a,b,c){Z3.call(this,a,b,c);
this.A=null;this.G=!1;this.C=null;this.B=!1;this.H=0;this.o=this.F=this.D=null},a4=function(a,b,c){Z3.call(this,a,b,c);
this.I=this.D=this.K=!1;this.G=5E3;this.B=null;this.H=g.ne("DIV","iv-promo-contents");this.A=this.C=this.o=null;this.F=new g.V(function(){this.o.setAttribute("aria-hidden",!0);g.N(this.C,!1);g.N(this.A,!0)},700,this);
g.M(this,this.F)},lEa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.sa().setAttribute("aria-hidden",!0);a.sa().setAttribute("aria-label","Promoci\u00f3n");a.sa().tabIndex=0;var e=a.annotation.Va(),f=b.image_url;if(f){var k=g.ne("DIV",["iv-promo-img","iv-click-target"]);f=g.ne("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.ne("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.ne("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.ol(k,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}e?(f=g.ne("A","iv-promo-txt"),g.md(f,a3(e)),a.o=f):a.o=g.ne("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.ne("P",null,g.ne("STRONG",null,b.text_line_1));var m=g.ne("P",null,g.ne("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
a.context.D.experiments.o("web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.ne("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.ne("BUTTON",["iv-button","iv-promo-button"],g.ne("SPAN","iv-button-content",f));var p=g.ne("DIV","iv-promo-button-container");p.appendChild(f);e&&a.ol(a.sa(),e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}g.S(a.o,"iv-click-target");e&&a.ol(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c);break;case "playlist":case "video":l=
g.ne("P",null,g.ne("SPAN",null,b.text_line_1)),m=g.ne("P",null,g.ne("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.ne("SPAN",["yt-badge","iv-promo-badge-live"],"EN DIRECTO AHORA")),g.S(a.o,"iv-click-target"),e&&a.ol(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);c=g.ne("DIV","iv-promo-actions");a.A=g.ne("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="Expandir";a.context.A.X(a.A,
"click",g.Na(a.Mu,5E3),a);c.appendChild(a.A);g.N(a.A,!1);a.context.A.X(a.sa(),"mouseover",a.qL,a);a.context.A.X(a.sa(),"mouseout",a.pL,a);a.context.A.X(a.sa(),"touchend",g.Na(a.Mu,5E3),a);a.C=g.ne("BUTTON",["iv-promo-close","ytp-button"]);a.C.title="Cerrar";a.context.A.X(a.C,"click","cta"==a.annotation.style&&b.text_line_3?a.fL:a.xO,a);c.appendChild(a.C);g.Or(a.sa(),d);k&&(a.sa().appendChild(k),n&&k.appendChild(n));a.sa().appendChild(a.H);a.sa().appendChild(c)},mEa=function(a){a.D||a.I||a.B||(g.S(a.sa(),
"iv-promo-collapsed"),a.D=!0,a.F.start())},nEa=function(a){a.F.stop();
a.D&&(g.Qr(a.sa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.D=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.N(a.A,!1),g.N(a.C,!0))},oEa=function(a,b){a.B||(a.B=g.jh(function(){b4(this);
mEa(this)},b,a))},b4=function(a){a.B&&(g.kh(a.B),a.B=null)},c4=function(a){g.lV.call(this,a);
this.K=!1;this.I=0;this.A={};this.L={};this.ib=new KDa(a);this.G=new g.QH(this);g.M(this,this.G);this.F=this.C=null;this.G.R(this.player,"onVideoAreaChange",(0,g.C)(this.U,this,"onVideoAreaChange"));this.G.R(this.player,"onHideControls",(0,g.C)(this.U,this,"onHideControls"));this.G.R(this.player,"onShowControls",(0,g.C)(this.U,this,"onShowControls"));this.G.R(this.player,"resize",(0,g.C)(this.U,this,"resize"));this.G.R(this.player,"presentingplayerstatechange",(0,g.C)(this.U,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.DR,this);this.subscribe("onShowControls",this.JT,this);this.subscribe("presentingplayerstatechange",this.PS,this);this.subscribe("resize",this.Tw,this);this.subscribe("G",this.EN,this);this.subscribe("F",this.ci,this);this.subscribe("D",this.mQ,this);this.subscribe("E",this.SQ,this);g.Y(this.player).I.subscribe("vast_info_card_add",this.cF,this);this.O=new g.QH(this);g.M(this,this.O);this.O.R(this.player,g.ZQ("annotations_module"),this.CN);this.O.R(this.player,
"crx_annotations_module",this.DN);this.V=g.ne("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Y=g.ne("DIV","video-custom-annotations");this.D=new g.W({J:"div",da:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.D);g.cV(this.player,this.D.element,4);this.D.hide();this.B=new g.W({J:"div",da:["ytp-iv-video-content"]});g.M(this,this.B);g.re(this.B.element,g.ne("DIV","video-annotations",this.V,this.Y));this.H=this.o=null;this.M=[];pEa(this)&&this.load();var b=g.pe("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Rf(this,function(){g.ve(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},qEa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},pEa=function(a){var b=g.Y(a.player);
a=a.player.getVideoData();return 1==(b.nh||a.nh)&&!a.Cl||null!==b.I.get(a.videoId)},rEa=function(a,b,c){a.K=!0;
a.F=g.AG(b,c)},sEa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(sEa(a,e))}return c},tEa=function(a,b,c){return!(a.loaded&&a.I==b&&a.player.getVideoData().videoId==
c)},vEa=function(a,b){var c=uEa(a,b);
if(!c&&"marker"!=b.type)return null;gDa(b,function(e){e=(0,g.C)(this.lU,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new y3(a.ha,b,c);g.M(d,c);return d},wEa=function(a,b){var c=g.ne("DIV",["annotation",
"annotation-type-custom"]);g.N(c,!1);var d=null;switch(b.type){case "branding":if(g.Y(a.player).Jl)break;a.D.element.appendChild(c);d=new $3(c,d4(a),b);break;case "promotion":g.cV(a.player,c,4),d=new a4(c,d4(a),b)}d&&d.Kr();return d},zEa=function(a){var b=a.player.getVideoData();
if(b.re){var c=g.Y(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",fd:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.fd.gaming="1");e.Hd=(0,g.C)(function(f,k,l){tEa(this,f,k)||(f=g.uG(l)&&l.responseXML?l.responseXML:null)&&e4(this,f)},a,a.I,b.videoId);
g.ZF()&&(e.Hd=xEa(a,e.Hd));e.Sb={ic_only:"1"};yEa(e,d);a.K=!0;g.AG(b.re,e)}}},yEa=function(a,b){a.method="POST";
a.Sb=a.Sb||{};b.Pt&&(a.Sb.ic_coll=b.Pt);b.zi&&(a.Sb.ic_xml=b.zi);b.tl&&(a.Sb.ic_track=b.tl)},AEa=function(a){var b=new g.W({J:"div"});
g.N(b.element,!1);var c=new W3(a.player,b.element,d4(a));g.M(c,b);b.A(a.D.element);c.Kr();return c},d4=function(a){if(!a.H){var b=new g.NH(a);
g.M(a,b);var c=new g.ho(a);g.M(a,c);a.H=new NDa(b,c,g.Y(a.player),a.player.getVideoData(),a.ib,a.player,a.ha)}return a.H},e4=function(a,b){var c=!1;
BEa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=sEa(a,d[e]),k=null;try{k=ICa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=wEa(a,k))g.M(a,f),a.L[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.o||(a.o=AEa(a),g.M(a,a.o)),"card"==k.type?fEa(a.o,k):gEa(a.o,k),c=!0;else if(f=vEa(a,k))g.M(a,f),a.A[k.id]=f}}c&&(j2(a.player),a.Tw());g.Pb(a.A,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.A&&
(m=this.A[m.segment.A])&&(l.O=m.annotation)}},a)},BEa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.WI();
if(b){var c=g.VI();c&&g.HI(b,c,[g.FI(a)])}}},DEa=function(a,b,c,d){d?CEa(a,b,c):f4(a,b,c)},f4=function(a,b,c){if(b=a.A[b])z3(b),c&&c.A?(a=(0,g.C)(a.bC,a,b),b.o=new g.V(a,2E3),b.o.start()):a.bC(b)},CEa=function(a,b,c){if(b=a.A[b])z3(b),c&&c.B?(a=(0,g.C)(a.hG,a,b),b.o=new g.V(a,2E3),b.o.start()):a.hG(b)},EEa=function(a,b){var c=a.player.getVideoData();
if(!c.No)return!1;var d=a3(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!R3(d))return!1;d=g.iG(d);return d.list||d.p?!1:(d=XDa(b))?c.videoId==d?!0:"new"!=b.target&&g.Y(a.player).o?!0:!1:!1},uEa=function(a,b){if(FEa(b)){var c=b.D||g3(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new t3(b,(0,g.C)(a.V.appendChild,a.V),a.player,a.ha,c)}return null},FEa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in f3)if(a.style==f3[b])return!0;return!1},g4=function(a,b,c,d){a.U(kDa(b,d),c,d)},xEa=function(a,b){return(0,g.C)(function(){if(!this.la()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Na.apply(window,c);this.M.push(g.XF(b))}},a)};
g.KU.prototype.kl=g.ca(13,function(a,b){var c=g.LU(this).B;c&&c.kl(a,b)});
var vBa=/[^\d]+$/,wBa={cm:1,"in":1,mm:1,pc:1,pt:1},xBa={em:1,ex:1};k2.prototype.clone=function(){return new k2(this.start,this.end)};
k2.prototype.getLength=function(){return this.end-this.start};
var l2={},m2=null;g.D(DBa,g.Uf);g.D(o2,g.cv);g.h=o2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.sb())return!1;n2(this);this.startTime=a=(0,g.K)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Qq();this.Oe("play");-1==this.o&&this.Oe("resume");this.o=1;var b=g.Ma(this);b in l2||(l2[b]=this);BBa();CBa(this,a);return!0};
g.h.stop=function(a){n2(this);this.o=0;a&&(this.progress=1);EBa(this,this.progress);this.Oe("stop");this.Dn()};
g.h.pause=function(){this.sb()&&(n2(this),this.o=-1,this.Oe("pause"))};
g.h.W=function(){0==this.o||this.stop(!1);this.Oe("destroy");o2.fa.W.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Kw=function(){this.Oe("animate")};
g.h.Oe=function(a){this.dispatchEvent(new DBa(a,this))};
g.D(p2,o2);p2.prototype.C=g.A;p2.prototype.Kw=function(){this.C();p2.fa.Kw.call(this)};
p2.prototype.Dn=function(){this.C();p2.fa.Dn.call(this)};
p2.prototype.Qq=function(){this.C();p2.fa.Qq.call(this)};
g.D(q2,p2);q2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.D(u2,g.vg);g.h=u2.prototype;g.h.Hu=null;g.h.Gm=null;g.h.sa=function(){return this.Gm};
g.h.addEventListener=function(a,b,c,d){g.gg(this.Gm,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.pg(this.Gm,a,b,c,d)};
g.h.W=function(){u2.fa.W.call(this);var a=this.Gm;if(a)if(g.$f(a))a.Pe&&g.dg(a.Pe);else if(a=g.jg(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.qg(d[e])&&++b}};g.D(y2,u2);y2.prototype.fill=null;g.D(KBa,u2);z2.prototype.Qf=null;z2.prototype.ee=null;z2.prototype.Xn=!0;var LBa=[2,2,6,6,0];g.h=z2.prototype;g.h.clear=function(){this.ub.length=0;this.Pa.length=0;this.Me.length=0;delete this.Qf;delete this.ee;delete this.Xn;return this};
g.h.moveTo=function(a,b){0==g.Sa(this.ub)?this.Me.length-=2:(this.ub.push(0),this.Pa.push(1));this.Me.push(a,b);this.ee=this.Qf=[a,b];return this};
g.h.Mc=function(a){var b=g.Sa(this.ub);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.ub.push(1),this.Pa.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Me.push(c,d)}this.Pa[this.Pa.length-1]+=b/2;this.ee=[c,d]};
g.h.close=function(){var a=g.Sa(this.ub);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.ub.push(4),this.Pa.push(1),this.ee=this.Qf);return this};
g.h.clone=function(){var a=new this.constructor;a.ub=this.ub.concat();a.Pa=this.Pa.concat();a.Me=this.Me.concat();a.Qf=this.Qf&&this.Qf.concat();a.ee=this.ee&&this.ee.concat();a.Xn=this.Xn;return a};
g.h.transform=function(a){if(!this.Xn)throw Error("Non-simple path");a.transform(this.Me,0,this.Me,0,this.Me.length/2);this.Qf&&a.transform(this.Qf,0,this.Qf,0,1);this.ee&&this.Qf!=this.ee&&a.transform(this.ee,0,this.ee,0,1);return this};
g.h.isEmpty=function(){return 0==this.ub.length};g.D(NBa,y2);B2.prototype.ab=function(){return this.A};g.D(C2,g.Bw);C2.prototype.C=null;C2.prototype.fk=function(){return this.bf?g.wi(this.sa()):g.Da(this.width)&&g.Da(this.height)?new g.Sd(this.width,this.height):null};
C2.prototype.resume=function(){};g.D(OBa,u2);g.D(w2,JBa);g.D(v2,JBa);g.D(D2,KBa);D2.prototype.clear=function(){g.te(this.sa())};
D2.prototype.setSize=function(a,b){G2(this.sa(),{width:a,height:b})};
g.D(PBa,NBa);g.D(E2,OBa);E2.prototype.setSize=function(a,b){G2(this.sa(),{width:a,height:b})};var I2;g.D(F2,C2);var RBa=0;g.h=F2.prototype;g.h.Lp=function(){var a=x2(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=x2(this,"g");this.H=x2(this,"defs");this.C=new D2(b,this);a.appendChild(this.H);a.appendChild(b);this.o=a;this.B&&(this.sa().setAttribute("preserveAspectRatio","none"),this.V?this.Yr():this.sa().setAttribute("viewBox","0 0 "+(this.B?this.B+" "+this.M:"")))};
g.h.Yr=function(){if(this.bf){var a=this.fk();if(0==a.width)this.sa().style.visibility="hidden";else{this.sa().style.visibility="";var b=a.width/this.B;a=a.height/this.M;this.C.sa().setAttribute("transform","scale("+b+" "+a+") translate(0 0)")}}};
g.h.setSize=function(a,b){g.vi(this.sa(),a,b)};
g.h.fk=function(){if(!g.fi)return this.bf?g.wi(this.sa()):F2.fa.fk.call(this);var a=this.width,b=this.height,c=g.x(a)&&-1!=a.indexOf("%"),d=g.x(b)&&-1!=b.indexOf("%");if(!this.bf&&(c||d))return null;if(c){var e=this.sa().parentNode;var f=g.wi(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.sa().parentNode,f=f||g.wi(e),b=parseFloat(b)*f.height/100);return new g.Sd(a,b)};
g.h.clear=function(){this.C.clear();g.te(this.H);this.A={}};
g.h.drawImage=function(a,b,c,d,e,f){a=x2(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new E2(a,this);(f||this.C).sa().appendChild(e.sa());return e};
g.h.Yj=function(){var a=this.fk();F2.fa.Yj.call(this);a||this.dispatchEvent("resize");if(this.V){a=this.width;var b=this.height;"string"==typeof a&&-1!=a.indexOf("%")&&"string"==typeof b&&-1!=b.indexOf("%")&&this.K.X(SBa(),"tick",this.Yr);this.Yr()}};
g.h.im=function(){F2.fa.im.call(this);this.V&&this.K.Ka(SBa(),"tick",this.Yr)};
g.h.W=function(){delete this.A;delete this.H;delete this.C;this.K.dispose();delete this.K;F2.fa.W.call(this)};g.t(K2,g.lV);g.h=K2.prototype;
g.h.load=function(){g.lV.prototype.load.call(this);if(!L2(g.Y(this.player).playerStyle)){var a=g.$oa(this.player.getVideoData());if(a)a=J2(a,TBa(this)),M2(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Hd:(0,g.C)(this.qR,this,a),fd:{v:a},withCredentials:!0};"gaming"==g.Y(this.player).playerStyle&&(a.fd.gaming="1");this.M&&(a.fd.ptype="embedded");var c=this.player.getVideoData().fB;c&&(a.Sb={ad_tracking:c});if(b=g.Zoa(b))if(b=g.Oc(b),b=g.Lc(b))this.B=
g.AG(b,a)}}};
g.h.unload=function(){M2(this,null);this.B&&(this.B.abort(),this.B=null);g.lV.prototype.unload.call(this)};
g.h.Kc=function(a,b){if(!L2(g.Y(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=J2(b,"new");M2(this,c);return!0}return null};
g.h.getOptions=function(){return L2(g.Y(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.qR=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=J2(c,TBa(this)))}M2(this,c)};
g.h.gD=function(){if(this.A&&this.A.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<GEa.length;f++){var k=Math.abs(b.width-GEa[f]);if(-1==e||d>=k)e=f,d=k}d=HEa[e];this.C&&g.ci(this.C.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.A.elements.length;++b)if(f=this.A.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.vi(e.element,Math.round(k.width*a.width),f);g.ki(e.element,m,n);g.Qr(e.element,IEa);m=k.left+k.width/2;k=k.top+l/2;g.S(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Qr(e.element,HEa);g.S(e.element,d);(e=g.Zd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ci(e,"height",f+"px")}}}}};
g.h.GN=function(a){if(this.A)if("ytp-ce-in-endscreen"==a.getId())this.K=!1,this.A.skip&&1==this.player.getPlayerState()?(g.SU(this.player,!0),this.player.seekTo(Infinity),this.K=!0):(P2(this,this.A.impressionUrls),(a=g.WI())&&this.A.visualElement&&g.II(a,this.A.visualElement));else if(!this.K){a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.S(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.S(b,"ytp-ce-shown");P2(this,c.impressionUrls);
(b=g.WI())&&g.II(b,c.visualElement);g.Y(this.player).Pb&&this.player.Ca("endscreenelementshown",a)}};
g.h.HN=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.K){a=a.getId().substring(15);var b=this.o[a];g.Pr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Pr(b,"ytp-ce-shown");g.Y(this.player).Pb&&this.player.Ca("endscreenelementhidden",a)}};
g.h.FU=function(a){var b=this;a.target===window&&(new g.V(function(){for(var c in b.o)g.Qr(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.yE=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Nr(c,"ytp-ce-element");){g.Nr(c,"subscribe-label")&&Q2(this,a);if(g.Nr(c,"ytp-ce-channel-subscribe"))return;c=g.Ae(c)}if(!c||g.Nr(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Sw(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Sr?(Q2(this,a),this.NF(),this.player.pauseVideo(),c=g.Oc(a.targetUrl),c=g.Lc(c),g.tV(c,void 0,a.Jd)):(c=this.player.getVideoData().Dc,
c=(0,g.C)(this.JV,this,c,a.targetUrl,a.Jd),c=(0,g.C)(this.NF,this,c),Q2(this,a,c))}}};
g.h.JV=function(a,b,c){var d=g.iG(b);a&&d&&(d.v||d.list)?g.O0(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.sV(b,c)};
g.h.ew=function(a,b){g.Nr(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.S(a.element,"ytp-ce-element-hover"):g.Y(this.player).A?(new g.V(function(){g.S(a.element,"ytp-ce-element-hover")},200)).start():g.S(a.element,"ytp-ce-element-hover"),P2(this,b.XL),O2(this,b.id,!0))};
g.h.Sw=function(a,b){g.Pr(a.element,"ytp-ce-element-hover");g.Pr(a.element,"ytp-ce-force-expand");O2(this,b.id,!1)};
g.h.NF=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var GEa=[346,426,470,506,570,640,853,1280,1920],HEa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),IEa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var eCa={ZY:"current",g1:"new"};var gCa={CLOSE:"close",m1:"openUrl",pJ:"subscribe"},hCa={Ns:"click",CLOSE:"close",t_:"hidden",l2:"rollOut",iJ:"rollOver",kJ:"shown"};var kCa={j4:"xx",l4:"xy",r4:"yx",s4:"yy"};g.t(qCa,c3);var wCa={PH:"anchored",X1:"rect",A2:"shapeless"};var BCa={CLOSED:"closed",v1:"playerControlShow",iJ:"rollOver",kJ:"shown"};e3.prototype.Va=function(){var a=MCa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
e3.prototype.showLinkIcon=function(){return g3(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var f3={PH:"anchored",SH:"branding",CHANNEL:"channel",YY:"cta",w_:"highlightText",Y_:"label",PLAYLIST:"playlist",J1:"popup",O2:"speech",pJ:"subscribe",o3:"title",VIDEO:"video",d4:"website"},GCa={SH:"branding",vY:"card",CZ:"drawer",v_:"highlight",u0:"marker",P1:"promotion",TEXT:"text",g4:"widget"},HCa={U3:"video_relative",w1:"player_relative"};lDa.prototype.B=function(a,b,c,d){this.o[a]=b?!c:c;a=g.Tb(this.o,function(e){return e});
this.C!=a&&(this.C=a,this.A.U(this.D,a,d))};j3.prototype.sa=function(){return this.D};
j3.prototype.C=function(){};var n3={bevel:1,dropshadow:2};g.t(p3,j3);
p3.prototype.C=function(a,b){var c=i3(a);if(c){var d=d3(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=iDa(a))&&c.o?c.o:null)&&c.length?c[0]:null){var f=g.Uh(mCa(b,nCa(e,new g.Rh(e.H,e.I,e.Bl,e.C),b.o))),k=d.clone();c=new g.Rh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.A;k=o3(k,c.effects);l=k3(this,k.width,k.height);m=tDa(c,k.width,k.height,
this.o);d=new g.Rh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Qd(f.x-k.left,f.y-k.top);this.B=17*b3(b.o,e.A,e.o?e.o:"xy");e=c.cornerRadius;f=a.A;var p=this.o&&h3(a),q=p?f.borderWidth+1:f.borderWidth;p=(f=q?new B2(q,p?f.A:f.borderColor):null)?f.ab()/2:0;q=vDa(d,n);var u=this.F(d,e,n,q),w=n.x;n=n.y;var B=d.width,G=d.height,H=d.left;d=d.top;var U=new z2;U.moveTo(H+e+p,d+p);"t"==q&&(U.Mc(u.start,d+p),U.Mc(w,n),U.Mc(u.end,d+p));U.Mc(H+B-e-p,d+p);A2(U,e,e,-90);"r"==q&&(U.Mc(H+B-p,u.start),
U.Mc(w,n),U.Mc(H+B-p,u.end));U.Mc(H+B-p,d+G-e-p);A2(U,e,e,0);"b"==q&&(U.Mc(u.end,d+G-p),U.Mc(w,n),U.Mc(u.start,d+G-p));U.Mc(H+e+p,d+G-p);A2(U,e,e,90);"l"==q&&(U.Mc(H+p,u.end),U.Mc(w,n),U.Mc(H+p,u.start));U.Mc(H+p,d+e+p);A2(U,e,e,180);U.close();H2(l,U,f,m);if(m=this.sa())g.S(m,"annotation-shape"),g.S(m,"annotation-speech-shape"),g.ki(m,k.left,k.top),g.vi(m,k.width,k.height),uDa(l,m,c.effects)}}}};
p3.prototype.F=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.Md(k-f/2,l+b,l+m-f-b);return new k2(k,k+f)}
return"t"==d||"b"==d?e(this.B,c.x,a.left,a.width):"l"==d||"r"==d?e(this.B,c.y,a.top,a.height):new k2(0,0)};g.t(q3,j3);q3.prototype.C=function(a,b){var c=i3(a);if(c){var d=d3(c,b);if(!(0>=d.width||0>=d.height)){var e=a.A;c=o3(d,e.effects);var f=k3(this,c.width,c.height),k=new g.Rh(0,0,d.width,d.height),l=e.cornerRadius;d=new B2(!e.C&&this.o?1:e.C,e.bgColor);var m=new v2("#000",0),n=d?d.ab()/2+1:0;k=sDa(k,l,n);H2(f,k,d,m);f=this.sa();g.S(f,"annotation-shape");e=e.o;g.yi(f,this.o?Math.max(e,.9):e);g.ki(f,c.left,c.top);g.vi(f,c.width,c.height)}}};g.t(r3,j3);
r3.prototype.C=function(a,b){var c=i3(a);if(c){var d=d3(c,b);if(!(0>=d.width||0>=d.height)){c=a.A;var e=o3(d,c.effects),f=k3(this,e.width,e.height),k=new g.Rh(0,0,d.width,d.height);d=tDa(c,d.width,d.height,this.o);var l=c.cornerRadius;var m=a.A;var n=this.o&&h3(a),p=n?m.borderWidth+1:m.borderWidth;n=(m=p?new B2(p,n?m.A:m.borderColor):null)?m.ab()/2+1:0;k=sDa(k,l,n);H2(f,k,m,d);if(k=this.sa())g.S(k,"annotation-shape"),g.S(k,"annotation-popup-shape"),g.ki(k,e.left,e.top),g.vi(k,e.width,e.height),uDa(f,
k,c.effects)}}};g.t(s3,p3);s3.prototype.F=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new k2(k,k+f)}
return"t"==d||"b"==d?e(this.B,c.x,a.left,a.width):"l"==d||"r"==d?e(this.B,c.y,a.top,a.height):new k2(0,0)};g.t(t3,g.L);g.h=t3.prototype;g.h.oD=function(){this.I||(this.B&&g.N(this.B,!0),this.D&&g.N(this.D,!0),this.C&&(this.C.o=!0,g.yi(this.A,x3(this)?1:0),this.C.C(this.o,v3(this))),this.H.isActive()&&this.H.stop(),this.I=!0,this.K=this.Z.Th(g.PU(this.F),"mouseleave",function(a){this.Oq.stop();this.ci(a)}))};
g.h.ci=function(){this.I&&(this.V?this.H.start():this.cC(),this.C&&(this.C.o=!1,g.yi(this.A,x3(this)?1:0),this.C.C(this.o,v3(this))),this.I=!1,this.K&&(this.Z.Ka(this.K),this.K=null))};
g.h.cC=function(){this.B&&g.N(this.B,!1);this.D&&g.N(this.D,!1)};
g.h.wO=function(a){this.ba=a;this.Oq.Em()};
g.h.oL=function(){var a=this.ba,b=new g.Qd(a.clientX,a.clientY),c=g.oi(this.F.getRootNode()),d=zDa(c,this.M);c=(this.D&&g.zi(this.D)||this.B&&g.zi(this.B))&&zDa(c,this.V);d&&d.contains(b)||c&&c.contains(b)?this.oD(a):this.ci(a)};
g.h.show=function(){var a=this.o.A;a=(a&&0==a.o||"title"==this.o.style||"highlightText"==this.o.style?!1:!0)&&!this.C;var b=!this.A;if(a){var c=v3(this),d=null;"highlight"==this.o.type||"label"==this.o.style?d=new q3:"popup"==this.o.style?d=new r3:"anchored"==this.o.style?d=new p3:"speech"==this.o.style&&(d=new s3);d&&(d.C(this.o,c),this.C=d,c=d.sa())&&(g.N(c,!1),g.S(c,"annotation-type-"+this.o.type.toLowerCase()),this.Y(c))}if(b){c=["annotation"];"highlightText"!=this.o.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.o.type.toLowerCase());this.A=g.ne("DIV",c);g.N(this.A,!1);this.o.B&&(this.G=g.ne("DIV","inner-text"),"label"==this.o.style&&(g.S(this.G,"player-label-text"),this.G.style.backgroundColor=this.o.A.bgColor),g.De(this.G,this.o.B),this.A.appendChild(this.G));g.BF(this.A,"annotation_id",this.o.id);this.Y(this.A);wDa(this,this.A);if(h3(this.o)&&this.o.showLinkIcon()){if(d=this.o.Va())c=this.A,d=new g.Rn(a3(d)),c.title=d.A+d.C;this.D=g.ne("SPAN","annotation-link-icon");g.N(this.D,
!1);this.A.appendChild(this.D)}xDa(this);h3(this.o)||(this.A.style.cursor="default")}if(a||b){a:{a=this.o.segment.o;if(a.length&&(a=yCa(a[0]))){a=a.D;break a}a=0}this.A&&(this.A.style.zIndex=a);this.C&&this.C.sa()&&(this.C.sa().style.zIndex=a)}g.N(this.A,!0);g.yi(this.A,x3(this)?1:0);w3(this);this.C&&this.C.sa()&&g.N(this.C.sa(),!0)};
g.h.hide=function(){this.A&&g.N(this.A,!1);this.C&&this.C.sa()&&g.N(this.C.sa(),!1);this.L&&(this.Z.Ka(this.L),this.L=null)};g.t(y3,g.L);g.h=y3.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(BDa(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.A.subscribe("resize",this.nD,this),this.A.subscribe("onVideoAreaChange",this.dF,this))};
g.h.destroy=function(){if(this.view){BDa(this);var a=this.view;g.OH(a.Z);a.Oq.dispose();a.H.dispose();a.A&&g.ve(a.A);a.C&&a.C.sa()&&g.ve(a.C.sa())}z3(this)};
g.h.dF=function(){w3(this.view)};
g.h.nD=function(){w3(this.view)};g.t(CDa,t2);g.t(A3,t2);g.t(DDa,A3);g.t(EDa,t2);g.t(FDa,t2);g.t(HDa,A3);g.t(IDa,A3);g.t(JDa,t2);g.t(B3,t2);K3.prototype.C=function(a,b){var c=g.Je(b.target,"label");c&&g.T(c,"iv-card-poll-choice-focused",a)};
K3.prototype.G=function(a,b){var c=g.Le(b.target,"iv-card-poll");if(c)if(a.B)g.ce("iv-card-sign-in-button",c).click();else{var d=parseInt(zBa(b.target),10);if(null==a.o)a.choices[d].count++,a.o=d;else if(a.o!=d){var e=a.choices[a.o];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.o=d}else e=a.choices[a.o],e.count=Math.max(e.count-1,0),a.o=null;ODa(a,c);g.EG(this.o.videoData.re,{fd:{action_poll_vote:1},Sb:{poll_id:a.id,index:d,session_token:a.I}});G3(this.o.logger,a.C,void 0,{"link-id":d},a.A.click,
5);(c=g.WI())&&g.JI(c,a.F)}};
K3.prototype.F=function(a){var b=g.z("yt.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.I,a.G)});
SDa(this,a,!0,c)};
K3.prototype.H=function(a){var b=g.z("yt.ypc.bootstrap.api.loadOffers");b&&(b=g.Na(b,a.M,a.I,a.G));SDa(this,a,!1,b)};g.t(T3,g.L);g.h=T3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.XQ(a,b,{id:c});g.M(this,a);a.namespace="annotations_module";d&&uBa(a).subscribe("onEnter",d,this);e&&uBa(a).subscribe("onExit",e,this);g.YU(this.context.o,[a])};
g.h.Kr=function(){this.context.C.subscribe("resize",this.Uo,this)};
g.h.sa=function(){return this.Ea};
g.h.ol=function(a,b,c,d,e,f,k){this.context.A.X(a,"click",g.Na(this.kq,b,c,d,e,f||[],k||0),this);this.context.A.X(a,"touchstart",g.Na(function(){this.Dy=!1}),this);
this.context.A.X(a,"touchmove",g.Na(function(){this.Dy=!0}),this)};
g.h.kq=function(a,b,c,d,e,f,k){if(this.Dy)return!1;k&&(k.stopPropagation(),k.preventDefault());$Da(this,a,c,d,e,f);return!1};
g.h.show=function(){this.ea=(0,g.K)()};
g.h.hide=function(){};
g.h.destroy=function(){g.ve(this.sa())};
g.h.Uo=function(){};g.t(W3,T3);g.h=W3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.C.length)(a=this.A.getRootNode())?(a=g.wi(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Uo=function(){var a=this.isAvailable();g.N(this.sa(),a);g.T(this.context.o.getRootNode(),"ytp-iv-drawer-enabled",a);j2(this.A)};
g.h.destroy=function(){this.A.kl(!1);this.A.getRootNode().removeChild(this.G);g.MF(this.L);g.DH(this.ba);this.ga&&this.ga.dispose();this.H&&this.H.dispose();T3.prototype.destroy.call(this)};
g.h.YN=function(a){this.V.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.VF=function(a){if(!g.Nr(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.WI(),c=this.o?this.o.kc.D:this.K;b&&c&&s2(b,[c]);this.o=a;X3(this)}g.zi(this.sa())&&(2==this.context.o.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.o.getAdState():void 0):(b=isNaN(void 0)?this.context.o.getPlayerState():void 0,b=1==b||0==b&&0===this.context.o.getCurrentTime()),b&&a.kc.teaserDurationMs&&this.A.kl(!0,{teaserText:a.kc.teaserText,durationMs:a.kc.teaserDurationMs}));this.ma.isActive()||
((!this.D||!this.V.isActive()&&this.aa)&&jEa(this,a),this.ma.start(910+a.kc.teaserDurationMs))}};
g.h.zV=function(a){this.D||(this.o=a,X3(this),jEa(this,a),U3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.eK=function(){if(this.D){I3(this.context.logger,this.Y,4,Y3(this).A.close);var a=g.WI();a&&this.M&&g.JI(a,this.M);V3(this)}};
g.h.pK=function(){g.T(this.G,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.fN=function(){var a=g.WI(),b=Y3(this);b=b?b.D:this.K;a&&b&&r2(a,[b])};
g.h.eN=function(){var a=g.WI(),b=Y3(this);b=b?b.D:this.K;a&&b&&s2(a,[b])};
g.h.iN=function(){var a=Y3(this);J3(this.context.logger,8,a.C,a.A.RV);var b=g.WI();b&&a&&r2(b,[a.H,a.D])};
g.h.hN=function(){var a=g.WI(),b=Y3(this);a&&b&&s2(a,[b.H])};
g.h.gN=function(a){var b=Y3(this),c=g.WI();this.o?a?(a=this.context.logger,J3(a,9,b.C,b.A.Ux),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.JI(c,b.H)):(a=this.context.logger,J3(a,12,b.C,b.A.Ux),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.JI(c,b.D)):(a=this.context.logger,I3(a,this.Y,12,b.A.Ux),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.K&&g.JI(c,this.K))};
var aEa={collaborator:CDa,donation:DDa,episode:B3,movie:B3,playlist:EDa,poll:FDa,productListing:HDa,simple:A3,tip:IDa,video:JDa};g.t(Z3,T3);Z3.prototype.Kr=function(){T3.prototype.Kr.call(this);kEa(this)};
Z3.prototype.show=function(){T3.prototype.show.call(this);var a=g.WI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&r2(a,[g.FI(b.itct)])};
Z3.prototype.hide=function(){T3.prototype.hide.call(this);var a=g.WI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&s2(a,[g.FI(b.itct)])};g.t($3,Z3);g.h=$3.prototype;g.h.KV=function(a,b,c,d){this.C.stop();if(!this.B){var e=g.wi(a);this.o||(g.ui(a,e.width),g.ui(b,e.width));g.ci(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ci(c,"right","1px");this.B=!0;g.N(a,!0);this.D=new g.V(function(){g.S(this.sa(),"iv-branding-active")},0,this);
this.D.start()}};
g.h.UL=function(a,b){g.Pr(this.sa(),"iv-branding-active");this.F=new g.V((0,g.C)(function(){g.N(a,!1);this.o||g.ui(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){Z3.prototype.show.call(this);if(!this.G){g.S(this.sa(),"iv-branding");var a=this.annotation.data;this.H=a.image_width;this.A=g.ne("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.N(this.A,!1);var b=g.ne("DIV","branding-img-container",this.A);this.sa().appendChild(b);var c=g.ne("DIV","iv-branding-context-name");g.De(c,a.channel_name);var d=g.ne("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=
new g.y_(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.o),this.o.A(d);b=g.ne("DIV","iv-branding-context-subscribe-caret");c=g.ne("DIV","branding-context-container-inner",b,c,d);g.N(c,!1);d=g.ne("DIV","branding-context-container-outer",c);g.ci(d,"right",this.H+"px");this.sa().appendChild(d);var e=this.annotation.Va();e&&this.ol(this.A,e,this.annotation.id,a.session_data,
this.annotation.o);this.C=new g.V(g.Na(this.UL,c,d),500,this);g.M(this,this.C);this.context.A.X(this.sa(),"mouseover",(0,g.C)(this.KV,this,c,d,b,a.image_height));this.context.A.X(this.sa(),"mouseout",(0,g.C)(this.C.start,this.C,void 0));this.G=!0}F3(this.context.logger,this.annotation.o);g.N(this.sa(),!0);this.isActive=!0;if(this.A){a=this.A;var f=void 0===f?0:f;b=g.xi(a).width;c=g.Da(void 0)?void 0:b;g.ki(a,c);f=new q2(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,FBa);g.M(this,f);this.context.B.X(f,
"begin",g.Na(g.N,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(Z3.prototype.hide.call(this),g.N(this.sa(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);Z3.prototype.destroy.call(this)};g.t(a4,Z3);g.h=a4.prototype;g.h.show=function(){this.isActive||(Z3.prototype.show.call(this),this.K||(lEa(this),this.K=!0),g.N(this.sa(),!0),this.annotation&&this.annotation.o&&F3(this.context.logger,this.annotation.o),g.jh(function(){g.Pr(this.sa(),"iv-promo-inactive")},100,this),this.sa().removeAttribute("aria-hidden"),this.isActive=!0,b4(this),nEa(this),oEa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.S(this.sa(),"iv-promo-inactive"),this.isActive=!1,this.sa().setAttribute("aria-hidden",!0))};
g.h.kq=function(a,b,c,d,e,f,k){return this.D?!1:Z3.prototype.kq.call(this,a,b,c,d,e,f,k)};
g.h.Mu=function(a,b){b.stopPropagation();nEa(this);oEa(this,a);this.o.focus()};
g.h.qL=function(a){this.I=!0;this.Mu(500,a)};
g.h.pL=function(){this.I=!1;mEa(this)};
g.h.xO=function(a){a.stopPropagation();this.hide();H3(this.context.logger,this.annotation.o)};
g.h.fL=function(a){a.stopPropagation();b4(this);this.D=!0;g.S(this.sa(),"iv-promo-collapsed-no-delay");this.F.start();H3(this.context.logger,this.annotation.o)};
g.h.destroy=function(){this.F.dispose();Z3.prototype.destroy.call(this)};g.t(c4,g.lV);g.h=c4.prototype;g.h.Kc=function(a,b){if(!qEa(g.Y(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Dt(b);c&&e4(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(cEa(this.o,b),j2(this.player)),!0}return null};
g.h.getOptions=function(){return qEa(g.Y(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Tw=function(){if(this.B){var a=g.PU(this.player).getVideoContentRect(!0);g.vi(this.B.element,a.width,a.height);g.ki(this.B.element,a.left,a.top)}if(this.o){var b=g.WU(this.player);a=this.o;b=b.width;g.T(a.G,"iv-drawer-small",426>=b);g.T(a.G,"iv-drawer-big",1280<=b)}};
g.h.PS=function(a){this.Qc(a.state);g.X(a.state,2)&&(this.be()&&this.se()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.kl(!1))};
g.h.load=function(){g.lV.prototype.load.call(this);this.Qc(g.OU(this.player));this.I++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.C)(this.uR,this,b,this.I),d=(0,g.C)(function(){this.F=null},this);
g.ZF()&&(c=xEa(this,c));c={format:"XML",Hd:c,onError:d,fd:{}};a.isPharma&&(c.fd.pharma="1");c.method="POST";c.withCredentials=!0;d=g.Y(this.player);"gaming"==d.playerStyle&&(c.fd.gaming="1");(b=d.I.get(b))&&yEa(c,b);b=b&&(b.zi||b.Pt);if(!a.Mo||b)a.re?rEa(this,a.re,c):(this.C=(0,g.C)(this.FN,this,c),this.player.addEventListener("videodatachange",this.C));g.cV(this.player,this.B.element,4);this.Tw()};
g.h.Qc=function(a){a=!a.isCued()&&!g.X(a,1024);g.WP(this.D,a);g.WP(this.B,a)};
g.h.FN=function(a){var b=this.player.getVideoData();b.re&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),rEa(this,b.re,a))};
g.h.unload=function(){LDa(this.ib);g.aV(this.player,"annotations_module");g.Pb(this.A,function(a){a.destroy()});
g.Pb(this.L,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,j2(this.player));this.K=!1;this.F&&(this.F.abort(),this.F=null);this.A={};this.L={};this.D.hide();g.lV.prototype.unload.call(this);g.VP(this.B);this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.h.uR=function(a,b,c){this.F=null;if(!tEa(this,b,a)&&(a=g.uG(c)&&c.responseXML?c.responseXML:null)){e4(this,a);g.S(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.A){b=this.A[d].annotation;if(b.segment)if(c=b.segment,c.o.length)if(c=c.o[0].A||c.o[0].o||c.o[0].C,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.B,f.visible=!0);b=new g.XQ(c,e,f);a.push(b)}}g.YU(this.player,a)}};
g.h.cF=function(a){a==this.player.getVideoData().videoId&&(this.loaded?zEa(this):this.load())};
g.h.CN=function(a){a=a.getId();var b=this.A[a];b&&!b.C&&(b=b.annotation,CEa(this,a),F3(this.ib,b.o))};
g.h.DN=function(a){f4(this,a.getId())};
g.h.bC=function(a){a&&(a.hide(),g4(this,"shown",!1,a.annotation.id),this.pp(a.annotation,"hidden"))};
g.h.hG=function(a){a&&(a.show(),g4(this,"shown",!0,a.annotation.id),this.pp(a.annotation,"shown"))};
g.h.lU=function(a,b,c){var d=this.A[a];if(d&&b.value!=c){b.value=c;var e=!1;gDa(d.annotation,function(f){e=e||f.value});
DEa(this,a,b,e)}};
g.h.mQ=function(a){if(a&&a.id){var b=a.Va();if(b){var c=a3(b);if(c){var d=(0,g.C)(this.pp,this,a,"click");if("new"==S3(c,b.target)||EEa(this,b))d(),d=null;G3(this.ib,a.o,d)}}}};
g.h.pp=function(a,b){JCa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!EEa(this,c.url))){e=XDa(c.url);var f=WDa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=d4(this).o,g.O0(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&d4(this).o.Nc()&&d4(this).o.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.Y(this.player),(d=a3(c.url))?(f=VDa(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Na(YDa,e.pageId,e.Rc),d=new g.Rn(d),g.Vn(d,e(d.C)),d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=S3(d,c.url.target),e=a.itct,"ei"in g.iG(d)&&(d=g.Kh(d,"ei")),g.tV(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.DR=function(){g4(this,"playerControlShow",!1)};
g.h.JT=function(){g4(this,"playerControlShow",!0)};
g.h.EN=function(a){g4(this,"rollOver",!0,a.id)};
g.h.ci=function(a){g4(this,"rollOver",!1,a.id)};
g.h.SQ=function(a){a&&a.id&&(this.A[a.id].C=!0,f4(this,a.id),H3(this.ib,a.o),this.pp(a,"close"),g4(this,"closed",!0,a.id))};
g.h.be=function(){return!!this.o&&this.o.isAvailable()};
g.h.se=function(){this.be();return!!this.o&&this.o.D};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.be();this.o&&(a?c?U3(this.o,c,b):U3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):V3(this.o))};
g.h.kl=function(a,b){this.player.U(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.W=function(){g.Y(this.player).I.unsubscribe("vast_info_card_add",this.cF,this);g.Pr(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.$F(a[b]);this.M.length=0;g.lV.prototype.W.call(this)};g.WZ.annotations_module=c4;g.WZ.creatorendscreen=K2;})(_yt_player);
